Add "ppc64le" to ArchUtils #1625.
See https://bugs.gentoo.org/972590
Bug 972590 - dev-java/commons-lang-3.20.0:
java.lang.NullPointerException: Cannot invoke
"org.apache.commons.lang3.arch.Processor.toString()" because
"&lt;local1&gt;"